import type { Metadata } from "next";
import { Geist, Geist_Mono, Staatliches } from "next/font/google";
import "./globals.css";
import { Navbar1 } from "@/components/navbar1";
import { SessionProvider } from "@/lib/session-context";
import { getSession } from "@/lib/service/user.service";
import { HeroSection } from "@/components/hero45";

import CallToAction from "@/components/ui/conversition";
import WhyChooseUs from "@/components/ui/whyChoose";
import { Hero47 } from "@/components/hero47";
import Premium from "@/components/ui/premium";
import CategoriesJob from "@/components/ui/categoriesJob";
import UrgentHiring from "@/components/ui/urgentHiring";
import TopCompanies from "@/components/ui/topCompanies";
import HowToApply from "@/components/ui/howtoApply";
import Statistics from "@/components/ui/statistics";
import Footer from "@/components/ui/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Job Hive Platform",
  description: "Generated By Job Hive Platform",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getSession();
  const initialUser = session.data?.data ?? null;
  return (
    <html
      lang="en"
      suppressHydrationWarning={true}
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
      <SessionProvider initialUser={initialUser}>
        <Navbar1 />

        <Hero47 />
        <HeroSection />
        <Premium />
        <CategoriesJob />
        <UrgentHiring />
        <TopCompanies />
        <HowToApply />
        <WhyChooseUs />
        <Statistics />
        <CallToAction />
        <main>{children}</main>
        <Footer />
      </SessionProvider>
    </html>
  );
}
